/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import clases.conectar;
import com.mysql.cj.protocol.Resultset;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stiven Baquero
 */
public class Registrar_alumnos extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_alumnos
     */
    public Registrar_alumnos() {
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        limpiar();
        txtid_alumno.setEnabled(false);
        
        mostrartabla("");
        cerrar();
        cargarcombocurso(cmb_materia);
        
        for(int i=0;i<=tabla_registros_alumnos.getRowCount();i++)
        {
        
        txtcantidad.setText(""+i);
        }
        
    }
    void limpiar(){
    
    txtid_alumno.setText("");
    txtnombre.setText("");
    txtapellido.setText("");
    txttelefono.setText("");
    cmb_grado.setSelectedIndex(0);
    cmb_materia.setSelectedIndex(0);
    }
    
    void mostrartabla(String valor){
    
    
    DefaultTableModel modelo=new DefaultTableModel();
    
    modelo.addColumn("Id");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Grado");
    modelo.addColumn("Materia");
    
    tabla_registros_alumnos.setModel(modelo);
    
    String sql="SELECT * FROM alumnos WHERE CONCAT(nombre,' ',apellido,' ',grado,' ',id_curso_asignado)LIKE '%"+valor+"%'";
    
    String datos[]=new String[6];
    Statement st;
    
        try {
            st=cn.createStatement();
             ResultSet rs=st.executeQuery(sql);
            
            while(rs.next()){
            
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            
            modelo.addRow(datos);
            
            tabla_registros_alumnos.setModel(modelo);
            
            
            }
        } catch (SQLException e) {
            
            System.err.println(e);
        }
    
    }
    
    public void cargarcombocurso(JComboBox combodelcurso){
    
        try {
            String sql="SELECT nombre_curso FROM curso";
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            
            while(rs.next()){
            
            combodelcurso.addItem(rs.getString("nombre_curso"));
            
            
            }
            
            
        } catch (SQLException e) {
            System.err.println(e);
        }
    
    }
    public void cerrar(){
    
        try {
            
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
            
                public void WindowClosing(WindowEvent e){
            
            confirmarsalida();
            
            }
            
            
            });
            
            
        } catch (Exception e) {
        }
    
    }
    
    public void confirmarsalida(){
    
    int valor=JOptionPane.showConfirmDialog
        (this, "¿desea cerrar la aplicacion ?","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
    if(valor==JOptionPane.YES_OPTION){
    
    JOptionPane.showMessageDialog(null, "Hasta pronto","",JOptionPane.INFORMATION_MESSAGE);
    System.exit(0);
    
    }
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popborrar = new javax.swing.JPopupMenu();
        popeliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid_alumno = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        cmb_grado = new javax.swing.JComboBox<>();
        cmb_materia = new javax.swing.JComboBox<>();
        btnagregar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_registros_alumnos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();

        popeliminar.setText("jMenuItem1");
        popeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popeliminarActionPerformed(evt);
            }
        });
        popborrar.add(popeliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar alumnos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumnos"));

        jLabel2.setText("Id alumno:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Grado:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Materia:");

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });

        cmb_grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione grado", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cmb_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione materia", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmb_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        tabla_registros_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_registros_alumnos.setComponentPopupMenu(popborrar);
        tabla_registros_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_registros_alumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_registros_alumnos);

        jLabel8.setText("Buscar:");

        jLabel9.setText("Cantidad:");

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnagregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnactualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnvolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addGap(35, 35, 35)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnagregar)
                            .addComponent(btnactualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnvolver)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
     
        String id_curso_asignado=cmb_materia.getSelectedItem().toString();
        String materia=(String)cmb_materia.getSelectedItem();
        String grado=(String)cmb_grado.getSelectedItem();
        
        try {
            
            if(txtnombre.getText().isEmpty())
            {
            
            JOptionPane.showMessageDialog(null, "No puede deja el campo nombre vacio");
            
            }
            ////////////////////////////////////////////////////////////////////////7
            
            else if(txtapellido.getText().isEmpty())
            {
            
            JOptionPane.showMessageDialog(null, "No puede deja el campo apellido vacio");
            
            }
            ///////////////////////////////////////////////////////////////////////////
            
            else if(txttelefono.getText().isEmpty())
            {
            
            JOptionPane.showMessageDialog(null, "No puede deja el campo telefono vacio");
            
            }
            //////////////////////////////////////////////////////////////////////////
            else if(grado.equals("Seleccione grado"))
            {
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Grado");
            
            }
            //////////////////////////////////////////////////////////////////////////////7
            else if(materia.equals("Seleccione materia"))
            {
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar un materia");
            
            }
            
            else{
            
                PreparedStatement ps=cn.prepareStatement("INSERT INTO alumnos(nombre,apellido,grado,telefono,id_curso_asignado)values(?,?,?,?,?)");
               
                ps.setString(1, txtnombre.getText());
                ps.setString(2, txtapellido.getText());
                ps.setString(3, cmb_grado.getSelectedItem().toString());
                ps.setString(4, txttelefono.getText());
                ps.setString(5, id_curso_asignado);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Alumno registrado con exito");
                mostrartabla("");
                limpiar();
              
                for(int i=0;i<=tabla_registros_alumnos.getRowCount();i++)
                {
                
                txtcantidad.setText(""+i);
                }
                
                
            }
            
            
            
            
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al guardar alumno");
        }
        
        
        
    }//GEN-LAST:event_btnagregarActionPerformed

    private void tabla_registros_alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_registros_alumnosMouseClicked
        
        int fila=this.tabla_registros_alumnos.getSelectedRow();
        this.txtid_alumno.setText(this.tabla_registros_alumnos.getValueAt(fila, 0).toString());
        this.txtnombre.setText(this.tabla_registros_alumnos.getValueAt(fila, 1).toString());
        this.txtapellido.setText(this.tabla_registros_alumnos.getValueAt(fila, 2).toString());
        this.cmb_grado.setSelectedItem(this.tabla_registros_alumnos.getValueAt(fila, 3).toString());
        this.txttelefono.setText(this.tabla_registros_alumnos.getValueAt(fila, 4).toString());
        this.cmb_materia.setSelectedItem(this.tabla_registros_alumnos.getValueAt(fila, 5).toString());
        
        
        
    }//GEN-LAST:event_tabla_registros_alumnosMouseClicked

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
       
        String materia=(String)cmb_materia.getSelectedItem();
        String grado=(String)cmb_grado.getSelectedItem();
        
        try {
            if(txtnombre.getText().isEmpty())
            {
            
            JOptionPane.showMessageDialog(null, "No puede dejar el campo nombre en blanco");
                     
            
            }
            
             /////////////////////////////////////////////////////////////////////////////
             else if(txtapellido.getText().isEmpty())
            {
            
            JOptionPane.showMessageDialog(null, "No puede deja el campo apellido vacio");
            
            }
            ///////////////////////////////////////////////////////////////////////////
            
            else if(txttelefono.getText().isEmpty())
            {
            
            JOptionPane.showMessageDialog(null, "No puede deja el campo telefono vacio");
            
            }
            //////////////////////////////////////////////////////////////////////////
            else if(grado.equals("Seleccione grado"))
            {
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Grado");
            
            }
            //////////////////////////////////////////////////////////////////////////////7
            else if(materia.equals("Seleccione materia"))
            {
            
            JOptionPane.showMessageDialog(null, "Debe seleccionar un materia");
            
            }
             
             //////////////////////////////////////
            else {
            
            PreparedStatement ps=cn.prepareStatement("UPDATE alumnos SET nombre='"+txtnombre.getText()+"',apellido='"+txtapellido.getText()+"',grado='"+cmb_grado.getSelectedItem().toString()+"',telefono='"+txttelefono.getText()+"',id_curso_asignado='"+cmb_materia.getSelectedItem().toString()+"' WHERE id_alumno='"+txtid_alumno.getText()+"'");
            int respuesta=ps.executeUpdate();
            if(respuesta>0){
            
            JOptionPane.showMessageDialog(null,"Datos del alumno modificados");
            limpiar();
            mostrartabla("");
            
            
            }
            else {
            
            JOptionPane.showMessageDialog(null,"No ha selecionado fila");
            
            
            
            }
            }
            
        } catch (SQLException e) {
            System.err.println(e);
            
            JOptionPane.showMessageDialog(null,"Error al actualizar alumno..comunicarse con el administrador");
        }
        
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void popeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popeliminarActionPerformed
      
        try {
            PreparedStatement ps=cn.prepareStatement("DELETE FROM alumnos WHERE id_alumno='"+txtid_alumno.getText()+"'");
            int respuesta=ps.executeUpdate();
            if(respuesta>0){
            
            JOptionPane.showMessageDialog(null,"alumno eliminado");
            limpiar();
            mostrartabla();
            
            for(int i=0;i<=tabla_registros_alumnos.getRowCount();i++)
            {
            
            txtcantidad.setText(""+i);
            
            
            
            }
            
            
            
            
            }
            else{
            
            JOptionPane.showMessageDialog(null, "No seleccionado fila");
            
            }
            
            
            
        } catch (SQLException e) {
            System.err.println(e);
            
            
            JOptionPane.showMessageDialog(null, "Error al eliminar el usuario..comunicarse con el administrador");
            
        }
        
        
    }//GEN-LAST:event_popeliminarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
       
        Principal principal=new Principal();
        principal.setVisible(true);
        dispose();
        
        
        
        
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        
        mostrartabla(txtbuscar.getText());
        
        for(int i=0;i<=tabla_registros_alumnos.getRowCount();i++)
        {
        
        txtcantidad.setText(""+i);
        }
        
        
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        
        
        char c=evt.getKeyChar();
        if((c<'a'||c>'z') && (c<'A')| c>'Z'&& c!=KeyEvent.VK_SPACE)evt.consume();
        
        
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
       
        char c=evt.getKeyChar();
        if((c<'a'||c>'z') && (c<'A')| c>'Z'&& c!=KeyEvent.VK_SPACE)evt.consume();
        
        
        
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
       
        char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        
        
    }//GEN-LAST:event_txttelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cmb_grado;
    private javax.swing.JComboBox<String> cmb_materia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popborrar;
    private javax.swing.JMenuItem popeliminar;
    private javax.swing.JTable tabla_registros_alumnos;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JButton txtcantidad;
    private javax.swing.JTextField txtid_alumno;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
conectar con=new conectar();
Connection cn=con.conexion();

    private void mostrartabla() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
