/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import clases.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Stiven Baquero
 */
public class Registrar_calificaciones extends javax.swing.JFrame {

    
    int idalumno=0;
    String nombre_alumno="";
    String nombre_curso="";
    
    /**
     * Creates new form Registrar_calificaciones
     */
    public Registrar_calificaciones() {
        initComponents();
        
   
        
        this.setLocationRelativeTo(null);
        
        txtnombre.setEditable(false);
        cmbcurso.setEnabled(false);
        
        
        cargarcombocurso(cmbcurso);
        
        idalumno=Gestion_alumnos.idalumno;
        
        
        try {
            
                 PreparedStatement ps=cn.prepareStatement("SELECT nombre FROM alumnos WHERE id_alumno='"+idalumno+"'");
            
                   ResultSet rs=ps.executeQuery();
                   
                   if(rs.next()){
                   
                   
                   nombre_alumno=rs.getNString("nombre");
                   
                   
                   }
                   
                   
                    
        } catch (SQLException e) {
            System.err.println(e);
            
            JOptionPane.showMessageDialog(null, "Error al consultar nombre del alumno");
            
        }
        
        txtnombre.setText(nombre_curso);
        
        //////////////////////////////////////////////////////////////
        
      try {
            
                 PreparedStatement ps=cn.prepareStatement("SELECT id_curso_asignado FROM alumnos WHERE id_alumno='"+idalumno+"'");
            
                   ResultSet rs=ps.executeQuery();
                   
                   if(rs.next()){
                   
                   
                   nombre_curso=rs.getNString("id_curso_asignado");
                   
                   
                   }
                   
                   
                    
        } catch (SQLException e) {
            System.err.println(e);
            
            JOptionPane.showMessageDialog(null, "Error al consultar curso del alumno");
            
        }
        
        cmbcurso.setSelectedItem(nombre_curso);
        
    }
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    public void cargarcombocurso(JComboBox combodelcurso){
    
        try {
            
            
            
            String sql="SELECT nombre_curso FROM curso";
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
                    
            
            while(rs.next()){
            
            
            combodelcurso.addItem(rs.getString("nombre_curso"));
            
            
            
            }
            
                    
                    
                    
                    
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "ERROR AL CARGAR DATOS EN COMBOX");
        }
    
    
    }
    
    /////////////////////////////
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttarea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbcurso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtcalificacion = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Calificaciones");

        jLabel2.setText("Alumno");

        jLabel3.setText("Tarea");

        jLabel4.setText("Curso");

        cmbcurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione curso" }));

        jLabel5.setText("Calificacion");

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel5))
                                .addComponent(txttarea, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(txtnombre)
                                .addComponent(cmbcurso, 0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnregistrar)
                                .addComponent(txtcalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnvolver)))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(txttarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cmbcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnregistrar)
                .addGap(18, 18, 18)
                .addComponent(btnvolver)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        
        String curso=cmbcurso.getSelectedItem().toString();
        
        try {
            
                    
              if(txttarea.getText().isEmpty())     {
              
              
              JOptionPane.showMessageDialog(null, "No puede dejar campo tarea vacio");
              
              } 
                 ////////////////////////////////////////   
                    
              else if(txtcalificacion.getText().isEmpty())     {
              
              
              JOptionPane.showMessageDialog(null, "No puede dejar campo Califacion vacio");
              
              }
              ///////////////////////////////////////////////
              
              else{
              
              
              
              PreparedStatement ps=cn.prepareStatement("INSERT INTO notas (id_alumno_nota,id_curso_nota,tarea,calificacion)Values (?,?,?,?)");
              ps.setInt(1,idalumno);
              ps.setString(2,curso);
              ps.setString(3,txttarea.getText());
              ps.setString(4,txtcalificacion.getText());
              
              ps.executeUpdate();
              
              JOptionPane.showMessageDialog(null, "Datos guardados");
              
              }
              
              
              
              
        } catch (SQLException e) {
            System.err.println(e);
            
            JOptionPane.showMessageDialog(null,"Error al guardar datos de calificaciones");
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
       
        informacion_alumnos Informacion_alumnos=new informacion_alumnos();
        Informacion_alumnos.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_calificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cmbcurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcalificacion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttarea;
    // End of variables declaration//GEN-END:variables
conectar con=new conectar();
Connection cn=con.conexion();

}
